# -*- coding: utf-8 -*-
"""FoodMed_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMiTGYBcmBxmlQaIhI38Zh3-bgiHq2Yw

# 🚀 **FoodMed AI**
### *AI that understands what you eat + what you say + predicts your health risk*

**Domain:** HealthTech + FoodTech  
**Tech:** Computer Vision (MobileNetV2), NLP (TF-IDF), ML (Random Forest)

---

### 🔹 Step 0 — Install & Setup
"""

!pip install tensorflow scikit-learn pandas matplotlib seaborn nltk
import nltk
nltk.download('punkt')

"""### 🔹 Step 1 — Import Libraries"""

import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns

"""---
##  1. COMPUTER VISION MODULE (Food Detection)

### 🔹 Step 2 — Upload Food Image
"""

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

img = Image.open(image_path).resize((224,224))
plt.imshow(img)
plt.axis('off')
plt.show()

"""### 🔹 Step 3 — Food Recognition Model"""

model = tf.keras.applications.MobileNetV2(weights='imagenet')
img_array = np.array(img)
img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)
img_array = np.expand_dims(img_array, axis=0)

preds = model.predict(img_array)
decoded = tf.keras.applications.mobilenet_v2.decode_predictions(preds, top=1)
food_detected = decoded[0][0][1]

print("Detected Item:", food_detected)

"""### 🔹 Step 4 — Nutrition Mapping"""

nutrition_db = {
    "pizza": [60, 25, 5],
    "burger": [50, 30, 6],
    "ice_cream": [45, 20, 30],
    "salad": [5, 1, 2],
    "rice": [80, 1, 0]
}

def map_food(food_name):
    food_name = food_name.lower()
    for key in nutrition_db:
        if key in food_name:
            return nutrition_db[key]
    return [20, 10, 5]

carbs, fat, sugar = map_food(food_detected)
print(f"Estimated Intake -> Carbs: {carbs}, Fat: {fat}, Sugar: {sugar}")

"""---
##  2. NLP MODULE (Lifestyle Sentiment)

### 🔹 Step 5 — User Lifestyle Input
"""

text_input = input("Describe your eating lifestyle: ")

sample_texts = [
    "I eat sweets daily and feel very tired",
    "I follow a strict healthy diet and exercise",
    "I avoid junk food and sugary drinks",
    "I eat outside frequently and love fried food",
    "I feel energetic and eat balanced meals"
]

vectorizer = TfidfVectorizer()
vectorizer.fit(sample_texts)

text_vec = vectorizer.transform([text_input]).toarray()
lifestyle_score = text_vec.sum()
print("Lifestyle AI Signal Score:", round(lifestyle_score, 4))

"""---
## 3. ML RISK MODEL (Predictive Analytics)

### 🔹 Step 6 — Train Multimodal Risk Model
"""

try:
    df = pd.read_csv('health_data.csv')
except:
    data = {
        "carbs": [70, 20, 90, 30, 60, 85, 55, 30],
        "fat": [30, 5, 40, 10, 20, 35, 15, 8],
        "sugar": [20, 2, 35, 5, 15, 25, 10, 4],
        "lifestyle": [2.5, 0.5, 3.0, 1.0, 2.0, 2.8, 0.8, 0.4],
        "risk": [1, 0, 1, 0, 1, 1, 0, 0]
    }
    df = pd.DataFrame(data)

X = df[["carbs", "fat", "sugar", "lifestyle"]]
y = df["risk"]

risk_model = RandomForestClassifier(n_estimators=100)
risk_model.fit(X, y)
print("Model trained.")

"""### 🔹 Step 7 — Final Multimodal Prediction"""

final_features = [[carbs, fat, sugar, lifestyle_score]]
prediction = risk_model.predict(final_features)
probability = risk_model.predict_proba(final_features)[0][1]

print(f"\n--- RESULTS ---")
print(f"Detected Food: {food_detected}")
print(f"Risk Probability: {round(probability * 100, 2)}%")

if prediction[0] == 1:
    print("⚠️ PREDICTION: HIGH FUTURE HEALTH RISK")
else:
    print("✅ PREDICTION: LOW FUTURE HEALTH RISK")

"""---
## 📊 4. VISUALIZATION MODULE

### 🔹 Step 8 — Visualize Results (Graphs)
"""

# Set visual style
sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Graph 1: Nutritional Content Comparison
labels = ['Carbs', 'Fat', 'Sugar']
values = [carbs, fat, sugar]
sns.barplot(x=labels, y=values, ax=ax1, palette="magma")
ax1.set_title(f'Nutritional Breakdown: {food_detected.upper()}', fontsize=15, fontweight='bold')
ax1.set_ylabel('Content Score / Grams')
for i, v in enumerate(values):
    ax1.text(i, v + 1, str(v), color='black', ha='center', fontweight='bold')

# Graph 2: Risk Probability Gauge (Pie Chart)
risk_data = [1 - probability, probability]
risk_labels = ['Safe Profile', 'Risk Profile']
colors = ['#2ecc71', '#e74c3c']

ax2.pie(risk_data, labels=risk_labels, autopct='%1.1f%%', colors=colors, startangle=90, explode=(0, 0.1), shadow=True)
ax2.set_title('Metabolic Health Risk Assessment', fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()